// Smoke import tests for every JS file under packages/**
// Ensures modules load without throwing and adds baseline coverage.

const modules = [
  // child
  '../child/check/blocking-css.js',
  '../child/check/both.js',
  '../child/check/calculation-mode.js',
  '../child/check/cross-domain.js',
  '../child/check/deprecated-attributes.js',
  '../child/check/ignored-elements.js',
  '../child/check/mode.js',
  '../child/check/overflow.js',
  '../child/check/quirks-mode.js',
  '../child/check/ready.js',
  '../child/check/settings.js',
  '../child/check/tags.js',
  '../child/check/tolerance.js',
  '../child/check/version.js',
  '../child/console.js',
  '../child/events/listeners.js',
  '../child/events/mouse.js',
  '../child/events/page-hide.js',
  '../child/events/print.js',
  '../child/events/ready.js',
  '../child/index.js',
  '../child/init.js',
  '../child/methods/auto-resize.js',
  '../child/methods/calculation-methods.js',
  '../child/methods/index.js',
  '../child/methods/move-to-anchor.js',
  '../child/methods/offset-size.js',
  '../child/methods/origin.js',
  '../child/methods/page-info.js',
  '../child/methods/parent-props.js',
  '../child/methods/proxy.js',
  '../child/methods/resize.js',
  '../child/methods/scroll.js',
  '../child/methods/send-message.js',
  '../child/observed/index.js',
  '../child/observed/mutation.js',
  '../child/observed/observers.js',
  '../child/observed/overflow.js',
  '../child/observed/resize.js',
  '../child/observed/visibility.js',
  '../child/observers/mutation.js',
  '../child/observers/overflow.js',
  '../child/observers/perf.js',
  '../child/observers/resize.js',
  '../child/observers/utils.js',
  '../child/observers/visibility.js',
  '../child/page/apply-selectors.js',
  '../child/page/clear-fix.js',
  '../child/page/css.js',
  '../child/page/links.js',
  '../child/page/reset.js',
  '../child/page/stop-infinite-resizing.js',
  '../child/read/from-page.js',
  '../child/read/from-parent.js',
  '../child/received/index.js',
  '../child/received/init.js',
  '../child/received/is.js',
  '../child/received/message.js',
  '../child/received/page-info.js',
  '../child/received/parent-info.js',
  '../child/received/process-request.js',
  '../child/received/reset.js',
  '../child/received/resize.js',
  '../child/received/utils.js',
  '../child/send/dispatch.js',
  '../child/send/message.js',
  '../child/send/size.js',
  '../child/size/all.js',
  '../child/size/auto.js',
  '../child/size/body-offset.js',
  '../child/size/change-detected.js',
  '../child/size/content.js',
  '../child/size/custom.js',
  '../child/size/get-height.js',
  '../child/size/get-new.js',
  '../child/size/get-width.js',
  '../child/size/index.js',
  '../child/size/max-element.js',
  '../child/utils/isolate.js',
  '../child/utils/map-settings.js',
  '../child/values/settings.js',
  '../child/values/state.js',
  // common
  '../common/consts.js',
  '../common/deprecate.js',
  '../common/format-advise.js',
  '../common/listeners.js',
  '../common/modal.js',
  '../common/mode.js',
  '../common/pubSub.js',
  '../common/utils.js',
  // core
  '../core/checks/id.js',
  '../core/checks/manual-logging.js',
  '../core/checks/mode.js',
  '../core/checks/options.js',
  '../core/checks/origin.js',
  '../core/checks/unique.js',
  '../core/checks/version.js',
  '../core/checks/warning-timeout.js',
  '../core/console.js',
  '../core/events/message.js',
  '../core/events/mouse.js',
  '../core/events/resize.js',
  '../core/events/size.js',
  '../core/events/visible.js',
  '../core/events/wrapper.js',
  '../core/index.js',
  '../core/listeners.js',
  '../core/methods/attach.js',
  '../core/methods/close.js',
  '../core/methods/disconnect.js',
  '../core/methods/reset.js',
  '../core/monitor/common.js',
  '../core/monitor/page-info.js',
  '../core/monitor/props.js',
  '../core/page/in-page-link.js',
  '../core/page/position.js',
  '../core/page/scroll.js',
  '../core/page/title.js',
  '../core/received/decode.js',
  '../core/received/message.js',
  '../core/received/preflight.js',
  '../core/router.js',
  '../core/send/offset.js',
  '../core/send/outgoing.js',
  '../core/send/ready.js',
  '../core/send/timeout.js',
  '../core/send/trigger.js',
  '../core/setup/body-margin.js',
  '../core/setup/direction.js',
  '../core/setup/first-run.js',
  '../core/setup/index.js',
  '../core/setup/init.js',
  '../core/setup/logging.js',
  '../core/setup/process-options.js',
  '../core/setup/scrolling.js',
  '../core/setup/target-origin.js',
  '../core/setup/update-option-names.js',
  '../core/values/defaults.js',
  '../core/values/page.js',
  '../core/values/settings.js',
  // jquery
  '../jquery/plugin.js',
  // legacy
  '../legacy/index.esm.js',
  '../legacy/js/iframeResizer.contentWindow.js',
  '../legacy/js/iframeResizer.js',
  '../legacy/js/notice.js',
  // parent
  '../parent/esm.js',
  '../parent/factory.js',
  '../parent/iife.js',
  '../parent/umd.js',
  // react
  '../react/index.jsx',
  // vue
  '../vue/index.js',
  // svelte
  '../svelte/index.js',
]

describe('packages smoke import', () => {
  for (const path of modules) {
    test(`imports ${path}`, async () => {
      // eslint-disable-next-line no-unsanitized/method
      const mod = await import(path)

      expect(mod).toBeDefined()
    }, 15_000)
  }
})
