export default ({
  license,
  bodyBackground,
  bodyMargin,
  bodyPadding,
  checkOrigin,
  direction,
  inPageLinks,
  log,
  logExpand,
  offsetSize,
  scrolling,
  tolerance,
  waitForLoad,
  warningTimeout,
  onAfterClose,
  onMessage,
  onMouseEnter,
  onMouseLeave,
  onReady,
  onResized,
  onScroll,
  ...iframeProps
}: Record<string, unknown>): Record<string, unknown> => iframeProps
