export default {
  applySelectors: null,
  firstRun: true,
  hasTags: false,
  hasOverflow: false,
  height: 0,
  isHidden: false,
  initLock: true,
  inPageLinks: {},
  origin: undefined,
  hasOverflowUpdated: true,
  overflowedNodeSet: new Set(),
  sameOrigin: false,
  taggedElements: [],
  target: window?.parent,
  timerActive: false,
  totalTime: 0,
  triggerLocked: false,
  width: 0,
  win: window,
  onPageInfo: null,
  onParentInfo: null,
}
