export default {
  applySelectors: null,
  firstRun: true,
  hasTags: false,
  hasOverflow: false,
  isHidden: false,
  initLock: true,
  inPageLinks: {},
  origin: undefined,
  overflowedNodeSet: new Set(),
  sameOrigin: false,
  taggedElements: [],
  target: window?.parent,
  triggerLocked: false,
  win: window,
  onPageInfo: null,
  onParentInfo: null,
}
