export default {
  applySelectors: null,
  firstRun: true,
  hasTags: false,
  hasOverflow: false,
  height: 0,
  isHidden: false,
  initLock: true,
  findInPageLinkTarget: null as ((location: string) => void) | null,
  origin: undefined,
  hasOverflowUpdated: true,
  overflowedNodeSet: new Set(),
  sameOrigin: false,
  taggedElements: [] as unknown as NodeListOf<Element>,
  target: window?.parent as MessageEventSource | null,
  timerActive: false,
  totalTime: 0,
  triggerLocked: false,
  width: 0,
  win: window,
  onPageInfo: null,
  onParentInfo: null,
}
